//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.ProductServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceRef.IMainContractOf_ProductData")]
    public interface IMainContractOf_ProductData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainContractOf_ProductData/GetAll", ReplyAction="http://tempuri.org/IMainContractOf_ProductData/GetAllResponse")]
        WCFContracts.DataContracts.ProductData[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainContractOf_ProductData/GetAll", ReplyAction="http://tempuri.org/IMainContractOf_ProductData/GetAllResponse")]
        System.Threading.Tasks.Task<WCFContracts.DataContracts.ProductData[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainContractOf_ProductData/Get", ReplyAction="http://tempuri.org/IMainContractOf_ProductData/GetResponse")]
        WCFContracts.DataContracts.ProductData Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainContractOf_ProductData/Get", ReplyAction="http://tempuri.org/IMainContractOf_ProductData/GetResponse")]
        System.Threading.Tasks.Task<WCFContracts.DataContracts.ProductData> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainContractOf_ProductData/GetPage", ReplyAction="http://tempuri.org/IMainContractOf_ProductData/GetPageResponse")]
        WCFContracts.DataContracts.ProductsViewModel GetPage(int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainContractOf_ProductData/GetPage", ReplyAction="http://tempuri.org/IMainContractOf_ProductData/GetPageResponse")]
        System.Threading.Tasks.Task<WCFContracts.DataContracts.ProductsViewModel> GetPageAsync(int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainContractOf_ProductData/Create", ReplyAction="http://tempuri.org/IMainContractOf_ProductData/CreateResponse")]
        void Create(WCFContracts.DataContracts.ProductData item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainContractOf_ProductData/Create", ReplyAction="http://tempuri.org/IMainContractOf_ProductData/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(WCFContracts.DataContracts.ProductData item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainContractOf_ProductData/Update", ReplyAction="http://tempuri.org/IMainContractOf_ProductData/UpdateResponse")]
        void Update(WCFContracts.DataContracts.ProductData item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainContractOf_ProductData/Update", ReplyAction="http://tempuri.org/IMainContractOf_ProductData/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(WCFContracts.DataContracts.ProductData item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainContractOf_ProductData/Delete", ReplyAction="http://tempuri.org/IMainContractOf_ProductData/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainContractOf_ProductData/Delete", ReplyAction="http://tempuri.org/IMainContractOf_ProductData/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainContractOf_ProductDataChannel : Shop.ProductServiceRef.IMainContractOf_ProductData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainContractOf_ProductDataClient : System.ServiceModel.ClientBase<Shop.ProductServiceRef.IMainContractOf_ProductData>, Shop.ProductServiceRef.IMainContractOf_ProductData {
        
        public MainContractOf_ProductDataClient() {
        }
        
        public MainContractOf_ProductDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainContractOf_ProductDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainContractOf_ProductDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainContractOf_ProductDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFContracts.DataContracts.ProductData[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<WCFContracts.DataContracts.ProductData[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public WCFContracts.DataContracts.ProductData Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<WCFContracts.DataContracts.ProductData> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public WCFContracts.DataContracts.ProductsViewModel GetPage(int page) {
            return base.Channel.GetPage(page);
        }
        
        public System.Threading.Tasks.Task<WCFContracts.DataContracts.ProductsViewModel> GetPageAsync(int page) {
            return base.Channel.GetPageAsync(page);
        }
        
        public void Create(WCFContracts.DataContracts.ProductData item) {
            base.Channel.Create(item);
        }
        
        public System.Threading.Tasks.Task CreateAsync(WCFContracts.DataContracts.ProductData item) {
            return base.Channel.CreateAsync(item);
        }
        
        public void Update(WCFContracts.DataContracts.ProductData item) {
            base.Channel.Update(item);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(WCFContracts.DataContracts.ProductData item) {
            return base.Channel.UpdateAsync(item);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
